#!/usr/bin/env bash
# Merge Cursor-injected secrets into gitignored .env.local.
# User secrets are available at agent boot, not during environment Builds.
set -euo pipefail
cd "$(dirname "$0")/.."
python3 - <<'PY'
from __future__ import annotations

import os
import secrets
from pathlib import Path

ROOT = Path.cwd()
PATH = ROOT / ".env.local"
PLACEHOLDERS = {
    "OAUTH_CLIENT_ID": {"", "dev-client-id"},
    "OAUTH_CLIENT_SECRET": {"", "dev-client-secret"},
    "SESSION_SECRET": {"", "dev-session-secret-change-me-please", "local-dev-session-secret", "youshouldreallychangethis"},
}

DEFAULTS = {
    "OAUTH_CLIENT_ID": "dev-client-id",
    "OAUTH_CLIENT_SECRET": "dev-client-secret",
    "OAUTH_SCOPES": (
        "read:self read:chat write:chat read:post write:post "
        "read:media write:media read:creator write:creator"
    ),
    "OAUTH_REDIRECT_URI": "http://localhost:3456/callback",
    "OAUTH_ISSUER_BASE_URL": "https://auth.fanvue.com",
    "API_BASE_URL": "https://api.fanvue.com",
    "SESSION_COOKIE_NAME": "fvsession",
    "SESSION_SECRET": "dev-session-secret-change-me-please",
    "BASE_URL": "http://localhost:3456",
    "TELEGRAM_BOT_TOKEN": "",
    "TELEGRAM_CHAT_ID": "",
    "FANVUE_TOKEN": "",
    "FANVUE_REFRESH_TOKEN": "",
    "FANVUE_TOKEN_EXPIRES_AT": "",
    "FANVUE_AGENT_REDIRECT_URI": "http://localhost:3456/callback",
}

KNOWN_KEYS = [
    "OAUTH_CLIENT_ID",
    "OAUTH_CLIENT_SECRET",
    "OAUTH_SCOPES",
    "OAUTH_REDIRECT_URI",
    "OAUTH_ISSUER_BASE_URL",
    "API_BASE_URL",
    "SESSION_COOKIE_NAME",
    "SESSION_SECRET",
    "BASE_URL",
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
    "FANVUE_TOKEN",
    "FANVUE_REFRESH_TOKEN",
    "FANVUE_TOKEN_EXPIRES_AT",
    "FANVUE_AGENT_REDIRECT_URI",
]


def parse_env(text: str) -> dict[str, str]:
    data: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        data[key.strip()] = value.strip().strip('"').strip("'")
    return data


def is_real(key: str, value: str) -> bool:
    return value not in PLACEHOLDERS.get(key, {""})


existing = parse_env(PATH.read_text(encoding="utf-8")) if PATH.exists() else {}
merged = dict(DEFAULTS)
merged.update({k: v for k, v in existing.items() if v})

def bot_id_from_token(token: str) -> str:
    token = (token or "").strip()
    return token.split(":", 1)[0] if ":" in token else ""


for key in DEFAULTS:
    env_val = os.environ.get(key, "").strip()
    if not env_val or not is_real(key, env_val):
        continue
    # Cursor secrets sometimes store a truncated client secret. Keep a longer
    # live value already on disk.
    if key == "OAUTH_CLIENT_SECRET" and is_real(key, merged.get(key, "")):
        if len(env_val) < len(merged[key]) and len(merged[key]) >= 32:
            continue
    # Cursor sometimes stores the bot's own id as TELEGRAM_CHAT_ID.
    if key == "TELEGRAM_CHAT_ID":
        bot_id = bot_id_from_token(
            merged.get("TELEGRAM_BOT_TOKEN") or os.environ.get("TELEGRAM_BOT_TOKEN") or ""
        )
        existing_chat = merged.get("TELEGRAM_CHAT_ID") or ""
        if env_val == bot_id or not env_val.isdigit():
            continue
        if existing_chat and existing_chat.isdigit() and existing_chat != bot_id and env_val == bot_id:
            continue
    merged[key] = env_val

if not is_real("SESSION_SECRET", merged["SESSION_SECRET"]):
    merged["SESSION_SECRET"] = secrets.token_urlsafe(32)

# Prefer a private user chat stored next to the Python agents.
agent_env = parse_env((ROOT / "fanvue-automation" / ".env").read_text(encoding="utf-8")) if (ROOT / "fanvue-automation" / ".env").exists() else {}
bot_id = bot_id_from_token(merged.get("TELEGRAM_BOT_TOKEN") or "")
file_chat = (agent_env.get("TELEGRAM_CHAT_ID") or "").strip()
current_chat = (merged.get("TELEGRAM_CHAT_ID") or "").strip()
if file_chat and file_chat != bot_id and file_chat.isdigit():
    if not current_chat or current_chat == bot_id or not current_chat.isdigit():
        merged["TELEGRAM_CHAT_ID"] = file_chat

skip_empty = {
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
    "FANVUE_TOKEN",
    "FANVUE_REFRESH_TOKEN",
    "FANVUE_TOKEN_EXPIRES_AT",
}
lines = ["# Generated by .cursor/write-env.sh. Do not commit."]
written = set()
for key in KNOWN_KEYS:
    value = merged.get(key, "")
    if key in skip_empty and not value:
        continue
    lines.append(f"{key}={value}")
    written.add(key)
for key, value in existing.items():
    if key in written or not value:
        continue
    lines.append(f"{key}={value}")
    written.add(key)
PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
PATH.chmod(0o600)

token_path = ROOT / "fanvue-automation" / "tokens.json"
access = merged.get("FANVUE_TOKEN") or ""
if access:
    import json as _json

    payload = {
        "access_token": access,
        "refresh_token": merged.get("FANVUE_REFRESH_TOKEN") or None,
        "token_type": "Bearer",
        "expires_at": int(merged.get("FANVUE_TOKEN_EXPIRES_AT") or "0" or "0"),
    }
    token_path.write_text(_json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    try:
        token_path.chmod(0o600)
    except OSError:
        pass

live = is_real("OAUTH_CLIENT_ID", merged["OAUTH_CLIENT_ID"]) and is_real(
    "OAUTH_CLIENT_SECRET", merged["OAUTH_CLIENT_SECRET"]
)
tokens = "tokens.json seeded" if access else "no FANVUE_TOKEN yet"
print("Wrote .env.local ({}; {})".format("Fanvue secrets present" if live else "placeholder credentials; app will boot, live login will 404", tokens))
PY
