#!/usr/bin/env bash
# Merge Cursor-injected secrets into gitignored .env.local.
# User secrets are available at agent boot, not during environment Builds.
set -euo pipefail
cd "$(dirname "$0")/.."
python3 - <<'PY'
from __future__ import annotations

import os
import secrets
from pathlib import Path

ROOT = Path.cwd()
PATH = ROOT / ".env.local"
PLACEHOLDERS = {
    "OAUTH_CLIENT_ID": {"", "dev-client-id"},
    "OAUTH_CLIENT_SECRET": {"", "dev-client-secret"},
    "SESSION_SECRET": {"", "dev-session-secret-change-me-please", "local-dev-session-secret", "youshouldreallychangethis"},
}

DEFAULTS = {
    "OAUTH_CLIENT_ID": "dev-client-id",
    "OAUTH_CLIENT_SECRET": "dev-client-secret",
    "OAUTH_SCOPES": (
        "read:self read:chat write:chat read:post write:post "
        "read:media write:media read:creator write:creator"
    ),
    "OAUTH_REDIRECT_URI": "http://localhost:3000/api/oauth/callback",
    "OAUTH_ISSUER_BASE_URL": "https://auth.fanvue.com",
    "API_BASE_URL": "https://api.fanvue.com",
    "SESSION_COOKIE_NAME": "fvsession",
    "SESSION_SECRET": "dev-session-secret-change-me-please",
    "BASE_URL": "http://localhost:3000",
    "TELEGRAM_BOT_TOKEN": "",
    "TELEGRAM_CHAT_ID": "",
}


def parse_env(text: str) -> dict[str, str]:
    data: dict[str, str] = {}
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        data[key.strip()] = value.strip().strip('"').strip("'")
    return data


def is_real(key: str, value: str) -> bool:
    return value not in PLACEHOLDERS.get(key, {""})


existing = parse_env(PATH.read_text(encoding="utf-8")) if PATH.exists() else {}
merged = dict(DEFAULTS)
merged.update({k: v for k, v in existing.items() if v})

for key in DEFAULTS:
    env_val = os.environ.get(key, "").strip()
    if env_val and is_real(key, env_val):
        merged[key] = env_val

if not is_real("SESSION_SECRET", merged["SESSION_SECRET"]):
    merged["SESSION_SECRET"] = secrets.token_urlsafe(32)

lines = [
    "# Generated by .cursor/write-env.sh. Do not commit.",
    f"OAUTH_CLIENT_ID={merged['OAUTH_CLIENT_ID']}",
    f"OAUTH_CLIENT_SECRET={merged['OAUTH_CLIENT_SECRET']}",
    f"OAUTH_SCOPES={merged['OAUTH_SCOPES']}",
    f"OAUTH_REDIRECT_URI={merged['OAUTH_REDIRECT_URI']}",
    f"OAUTH_ISSUER_BASE_URL={merged['OAUTH_ISSUER_BASE_URL']}",
    f"API_BASE_URL={merged['API_BASE_URL']}",
    f"SESSION_COOKIE_NAME={merged['SESSION_COOKIE_NAME']}",
    f"SESSION_SECRET={merged['SESSION_SECRET']}",
    f"BASE_URL={merged['BASE_URL']}",
]
if merged.get("TELEGRAM_BOT_TOKEN"):
    lines.append(f"TELEGRAM_BOT_TOKEN={merged['TELEGRAM_BOT_TOKEN']}")
if merged.get("TELEGRAM_CHAT_ID"):
    lines.append(f"TELEGRAM_CHAT_ID={merged['TELEGRAM_CHAT_ID']}")
PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
PATH.chmod(0o600)

live = is_real("OAUTH_CLIENT_ID", merged["OAUTH_CLIENT_ID"]) and is_real(
    "OAUTH_CLIENT_SECRET", merged["OAUTH_CLIENT_SECRET"]
)
print("Wrote .env.local ({})".format("Fanvue secrets present" if live else "placeholder credentials; app will boot, live login will 404"))
PY
